### PR TITLE
trying newer instanbul

### PR DESCRIPTION
**Pull request by PommeVerte**
Temp PR just to check build and coverage. You can ignore for now.

### CODE REVIEW

**Comment by PommeVerte** [comment]
Ok, so basically this PR updates istanbul. What comes from this is that before this PR the coverage was done on the `lib/*` files. This is 1) giving an incorrect result and 2) means you can't get file reports in coveralls.
 
This PR fixes this and uses `src/*` files correctly. Though the file reports seem very minimal, it seems to only tell you which methods are being checked? see here : https://coveralls.io/builds/5500079/source?filename=src%2FGremlinClient.js

I don't know if this is a normal level of coverage report from istanbul/JS or if I'm still getting something wrong. 
Coming from php our file reports tell us how many times each line is executes which is pretty different. For instance, it's obvious that I haven't tested the case of a `close()` on an open transaction.
image
I was hoping istanbul would provide something similar. hmmm

**Comment by PommeVerte** [comment]
Actually I'm pretty sure It's not working right yet. Lets put this on hold

**Comment by PommeVerte** [comment]
FYI I got this working on gremlin-console with karma and browser tests. So I'll change this PR to include that configuration if you're cool with it.

**Comment by jbmusso** [comment]
Ah that's cool! Sure, go ahead. Thanks.

**Comment by PommeVerte** [comment]
Closing this in favor of PR#45

**Pull request closed without merging**
